import { db } from "./db";
import {
  events,
  organisations,
  businesses,
  artists,
  perks,
  venues,
  cpids,
} from "@shared/schema";

function generateCPID(prefix: string): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let result = "";
  for (let i = 0; i < 6; i++) {
    result += chars[Math.floor(Math.random() * chars.length)];
  }
  return `${prefix}${result}`;
}

async function seed() {
  console.log("Seeding database...");

  const existingEvents = await db.select().from(events);
  if (existingEvents.length > 0) {
    console.log("Database already seeded. Skipping.");
    process.exit(0);
  }

  const orgData = [
    {
      name: "Kerala Samajam Sydney",
      description: "Bringing the Keralite community together through cultural events, festivals, and social gatherings across Greater Sydney.",
      city: "Sydney",
      state: "NSW",
      memberCount: 1200,
      imageUrl: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=600",
      cpid: generateCPID("CP-ORG-"),
      established: "2005",
      categories: ["Cultural", "Social"],
      slug: "kerala-samajam-sydney",
      website: "https://keralasamajamsydney.org.au",
      socialLinks: { facebook: "https://facebook.com/keralasamajamsydney", instagram: "https://instagram.com/keralasamajamsyd" },
    },
    {
      name: "Melbourne Malayalam Association",
      description: "Celebrating Malayalam language and Kerala culture in Melbourne through literary events, Onam celebrations, and youth programs.",
      city: "Melbourne",
      state: "VIC",
      memberCount: 850,
      imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600",
      cpid: generateCPID("CP-ORG-"),
      established: "2008",
      categories: ["Cultural", "Language"],
      slug: "melbourne-malayalam-assoc",
      website: "https://melbournemalayalam.org.au",
      socialLinks: { facebook: "https://facebook.com/melbournemalayalam", youtube: "https://youtube.com/@melbmalayalam" },
    },
    {
      name: "Pravasi Malayali Association Brisbane",
      description: "Supporting the Keralite diaspora in Queensland through community welfare, cultural festivals, and professional networking.",
      city: "Brisbane",
      state: "QLD",
      memberCount: 420,
      imageUrl: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=600",
      cpid: generateCPID("CP-ORG-"),
      established: "2012",
      categories: ["Social", "Welfare"],
      slug: "pravasi-malayali-brisbane",
    },
    {
      name: "Kerala Arts & Sports Club Perth",
      description: "Promoting traditional Kerala arts, sports tournaments, and family-friendly cultural gatherings in Perth.",
      city: "Perth",
      state: "WA",
      memberCount: 310,
      imageUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=600",
      cpid: generateCPID("CP-ORG-"),
      established: "2015",
      categories: ["Arts", "Sports"],
      slug: "kerala-arts-sports-perth",
    },
    {
      name: "Adelaide Keraleeya Samithi",
      description: "A vibrant community fostering Kerala traditions, Vishu celebrations, and interfaith harmony in South Australia.",
      city: "Adelaide",
      state: "SA",
      memberCount: 260,
      imageUrl: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600",
      cpid: generateCPID("CP-ORG-"),
      established: "2010",
      categories: ["Cultural", "Religious"],
      slug: "adelaide-keraleeya-samithi",
    },
  ];

  const insertedOrgs = await db.insert(organisations).values(orgData).returning();
  for (const org of insertedOrgs) {
    if (org.cpid) await db.insert(cpids).values({ cpid: org.cpid, entityType: "organisation", entityId: org.id });
  }
  console.log(`Inserted ${insertedOrgs.length} organisations`);

  const eventData = [
    {
      title: "Onam Grand Celebration 2026",
      description: "Experience the joy of Onam with traditional Sadya, Thiruvathira dance, Pulikali parade, boat race miniatures, and a spectacular cultural program.",
      category: "Festival",
      date: "2026-09-14",
      time: "10:00",
      endTime: "22:00",
      venue: "Sydney Olympic Park",
      city: "Sydney",
      state: "NSW",
      imageUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600",
      price: 25,
      orgId: insertedOrgs[0].id,
      orgName: "Kerala Samajam Sydney",
      featured: true,
      trending: true,
      cpid: generateCPID("CP-E-"),
    },
    {
      title: "Vishu Kani Celebration",
      description: "Ring in the Malayalam New Year with traditional Vishukkani setup, Sadya feast, fireworks, and family entertainment.",
      category: "Festival",
      date: "2026-04-14",
      time: "08:00",
      endTime: "18:00",
      venue: "Parramatta Park",
      city: "Sydney",
      state: "NSW",
      imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600",
      price: 15,
      orgId: insertedOrgs[0].id,
      orgName: "Kerala Samajam Sydney",
      featured: true,
      trending: false,
      cpid: generateCPID("CP-E-"),
    },
    {
      title: "Kathakali Masterclass Evening",
      description: "A mesmerising evening of Kathakali performances by renowned artists from Kerala, followed by audience Q&A and makeup demonstration.",
      category: "Dance",
      date: "2026-05-20",
      time: "18:00",
      endTime: "21:00",
      venue: "Melbourne Arts Centre",
      city: "Melbourne",
      state: "VIC",
      imageUrl: "https://images.unsplash.com/photo-1508700929628-666bc8bd84ea?w=600",
      price: 35,
      orgId: insertedOrgs[1].id,
      orgName: "Melbourne Malayalam Association",
      featured: true,
      trending: true,
      cpid: generateCPID("CP-E-"),
    },
    {
      title: "Malayalam Film Festival 2026",
      description: "Three days of the finest Malayalam cinema - award-winning films, director panels, and special screening of unreleased titles.",
      category: "Film",
      date: "2026-06-12",
      time: "14:00",
      endTime: "22:00",
      venue: "Palace Cinemas",
      city: "Melbourne",
      state: "VIC",
      imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600",
      price: 20,
      orgId: insertedOrgs[1].id,
      orgName: "Melbourne Malayalam Association",
      featured: false,
      trending: true,
      cpid: generateCPID("CP-E-"),
    },
    {
      title: "Mohiniyattam Workshop",
      description: "Learn the graceful classical dance form of Kerala - Mohiniyattam. Open to all skill levels. Includes costume and performance opportunity.",
      category: "Dance",
      date: "2026-03-15",
      time: "09:00",
      endTime: "13:00",
      venue: "Brisbane Multicultural Centre",
      city: "Brisbane",
      state: "QLD",
      imageUrl: "https://images.unsplash.com/photo-1547153760-18fc86c8a36f?w=600",
      price: 30,
      orgId: insertedOrgs[2].id,
      orgName: "Pravasi Malayali Association Brisbane",
      featured: false,
      trending: false,
      cpid: generateCPID("CP-E-"),
    },
    {
      title: "Kerala Food Festival",
      description: "Savour authentic Kerala cuisine - Appam, Puttu, Biriyani, Fish Curry, and a grand Sadya spread. Live cooking demonstrations included.",
      category: "Food",
      date: "2026-07-18",
      time: "11:00",
      endTime: "20:00",
      venue: "Federation Square",
      city: "Melbourne",
      state: "VIC",
      imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600",
      price: 10,
      orgId: insertedOrgs[1].id,
      orgName: "Melbourne Malayalam Association",
      featured: true,
      trending: true,
      cpid: generateCPID("CP-E-"),
    },
    {
      title: "Thiruvathira Night",
      description: "Traditional Thiruvathira dance competition followed by community dinner and cultural program. Open to all age groups.",
      category: "Dance",
      date: "2026-08-22",
      time: "17:00",
      endTime: "22:00",
      venue: "Perth Convention Centre",
      city: "Perth",
      state: "WA",
      imageUrl: "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=600",
      price: 18,
      orgId: insertedOrgs[3].id,
      orgName: "Kerala Arts & Sports Club Perth",
      featured: false,
      trending: false,
      cpid: generateCPID("CP-E-"),
    },
    {
      title: "Malayalam Poetry & Literature Evening",
      description: "An intimate gathering celebrating Malayalam poetry and prose. Readings, discussions, and book launches by Australian-Malayalam authors.",
      category: "Literature",
      date: "2026-04-28",
      time: "18:30",
      endTime: "21:00",
      venue: "State Library of SA",
      city: "Adelaide",
      state: "SA",
      imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600",
      price: 0,
      orgId: insertedOrgs[4].id,
      orgName: "Adelaide Keraleeya Samithi",
      featured: false,
      trending: false,
      cpid: generateCPID("CP-E-"),
    },
    {
      title: "Christmas Carol by Kerala Choir",
      description: "Beautiful Christmas carols in Malayalam and English performed by the Kerala Christian Choir of Sydney. Free entry, donations welcome.",
      category: "Music",
      date: "2026-12-20",
      time: "18:00",
      endTime: "20:30",
      venue: "St Mary's Cathedral",
      city: "Sydney",
      state: "NSW",
      imageUrl: "https://images.unsplash.com/photo-1543364195-bfe6e4932397?w=600",
      price: 0,
      orgId: insertedOrgs[0].id,
      orgName: "Kerala Samajam Sydney",
      featured: false,
      trending: false,
      cpid: generateCPID("CP-E-"),
    },
    {
      title: "Kerala Cricket Tournament",
      description: "Annual inter-community cricket tournament for the Malayalee community. Teams from all Australian states compete for the CulturePass Trophy.",
      category: "Sports",
      date: "2026-11-08",
      time: "07:00",
      endTime: "18:00",
      venue: "Roper Reserve",
      city: "Melbourne",
      state: "VIC",
      imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600",
      price: 5,
      orgId: insertedOrgs[1].id,
      orgName: "Melbourne Malayalam Association",
      featured: false,
      trending: true,
      cpid: generateCPID("CP-E-"),
    },
    {
      title: "Theyyam & Kalaripayattu Show",
      description: "Witness the power of Kerala's ancient martial art Kalaripayattu and the divine ritual art form Theyyam, brought to life by masters from Kannur.",
      category: "Cultural",
      date: "2026-10-05",
      time: "16:00",
      endTime: "20:00",
      venue: "Riverside Theatres",
      city: "Sydney",
      state: "NSW",
      imageUrl: "https://images.unsplash.com/photo-1545959570-a94084071b5d?w=600",
      price: 40,
      orgId: insertedOrgs[0].id,
      orgName: "Kerala Samajam Sydney",
      featured: true,
      trending: true,
      cpid: generateCPID("CP-E-"),
    },
    {
      title: "Youth Talent Night",
      description: "Young Malayalee talent in Australia showcase singing, dancing, comedy, and instrumentals. Prizes for top performers in each category.",
      category: "Music",
      date: "2026-06-28",
      time: "17:00",
      endTime: "21:00",
      venue: "Canberra Theatre",
      city: "Canberra",
      state: "ACT",
      imageUrl: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600",
      price: 12,
      orgName: "CulturePass Community",
      featured: false,
      trending: false,
      cpid: generateCPID("CP-E-"),
    },
  ];

  const insertedEvents = await db.insert(events).values(eventData).returning();
  for (const ev of insertedEvents) {
    if (ev.cpid) await db.insert(cpids).values({ cpid: ev.cpid, entityType: "event", entityId: ev.id });
  }
  console.log(`Inserted ${insertedEvents.length} events`);

  const bizData = [
    {
      name: "Malabar Spice Kitchen",
      description: "Authentic Kerala cuisine restaurant serving traditional Malabar dishes, Sadya, and fusion specials. Catering available for events.",
      category: "Restaurant",
      city: "Sydney",
      state: "NSW",
      phone: "+61 2 9123 4567",
      website: "https://malabarspice.com.au",
      imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600",
      cpid: generateCPID("CP-B-"),
      rating: 4.7,
      isSponsor: true,
      socialLinks: { facebook: "https://facebook.com/malabarspicekitchen", instagram: "https://instagram.com/malabarspiceau" },
    },
    {
      name: "Kochi Express",
      description: "Fast-casual Kerala food - biriyani, parotta, and curries. Perfect for quick authentic Malayalee meals on the go.",
      category: "Restaurant",
      city: "Melbourne",
      state: "VIC",
      phone: "+61 3 9456 7890",
      website: "https://kochiexpress.com.au",
      imageUrl: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600",
      cpid: generateCPID("CP-B-"),
      rating: 4.5,
      isSponsor: false,
    },
    {
      name: "Kerala Ayurveda Wellness",
      description: "Traditional Ayurvedic treatments, Panchakarma therapy, and wellness consultations by certified Ayurvedic practitioners from Kerala.",
      category: "Health & Wellness",
      city: "Sydney",
      state: "NSW",
      phone: "+61 2 9876 5432",
      website: "https://keralaayurveda.com.au",
      imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600",
      cpid: generateCPID("CP-B-"),
      rating: 4.8,
      isSponsor: true,
    },
    {
      name: "Munnar Tea Boutique",
      description: "Premium teas sourced directly from Munnar estates. Single-origin, organic Kerala tea, spices, and handcraft hampers.",
      category: "Retail",
      city: "Brisbane",
      state: "QLD",
      phone: "+61 7 3321 5678",
      website: "https://munnartea.com.au",
      imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600",
      cpid: generateCPID("CP-B-"),
      rating: 4.6,
      isSponsor: false,
    },
    {
      name: "Thejas Photography",
      description: "Professional photography and videography services specialising in cultural events, weddings, and traditional ceremonies.",
      category: "Photography",
      city: "Melbourne",
      state: "VIC",
      phone: "+61 3 9321 4567",
      website: "https://thejasphoto.com.au",
      imageUrl: "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=600",
      cpid: generateCPID("CP-B-"),
      rating: 4.9,
      isSponsor: false,
    },
    {
      name: "Kairali Silks",
      description: "Authentic Kerala Kasavu sarees, Mundus, and traditional garments for festivals and ceremonies. Custom tailoring available.",
      category: "Fashion",
      city: "Sydney",
      state: "NSW",
      phone: "+61 2 9432 1098",
      website: "https://kairalisilks.com.au",
      imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600",
      cpid: generateCPID("CP-B-"),
      rating: 4.4,
      isSponsor: true,
    },
  ];

  const insertedBiz = await db.insert(businesses).values(bizData).returning();
  for (const biz of insertedBiz) {
    if (biz.cpid) await db.insert(cpids).values({ cpid: biz.cpid, entityType: "business", entityId: biz.id });
  }
  console.log(`Inserted ${insertedBiz.length} businesses`);

  const artistData = [
    {
      name: "Meera Krishnamurthy",
      genre: "Classical Dance (Bharatanatyam & Mohiniyattam)",
      bio: "Award-winning classical dancer trained at Kerala Kalamandalam. Meera has performed across Australia and India, bringing the grace of Mohiniyattam to international stages.",
      imageUrl: "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=600",
      city: "Sydney",
      state: "NSW",
      featured: true,
      cpid: generateCPID("CP-AR-"),
      performances: 120,
      slug: "meera-krishnamurthy",
      website: "https://meerakrishnamurthy.com",
      socialLinks: { instagram: "https://instagram.com/meeradance", youtube: "https://youtube.com/@meerakrishnamurthy" },
    },
    {
      name: "Arjun Menon",
      genre: "Carnatic Vocal & Fusion Music",
      bio: "Carnatic musician blending traditional ragas with contemporary sounds. Has released 3 albums and performed at festivals across Australia.",
      imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600",
      city: "Melbourne",
      state: "VIC",
      featured: true,
      cpid: generateCPID("CP-AR-"),
      performances: 85,
      slug: "arjun-menon",
      socialLinks: { facebook: "https://facebook.com/arjunmenonmusic", instagram: "https://instagram.com/arjunmenon" },
    },
    {
      name: "Lakshmi Nair",
      genre: "Kathakali & Theatre",
      bio: "One of Australia's leading Kathakali artists. Lakshmi combines ancient storytelling with modern theatrical techniques, creating unforgettable performances.",
      imageUrl: "https://images.unsplash.com/photo-1508700929628-666bc8bd84ea?w=600",
      city: "Brisbane",
      state: "QLD",
      featured: true,
      cpid: generateCPID("CP-AR-"),
      performances: 65,
      slug: "lakshmi-nair",
    },
    {
      name: "Vishnu Dev",
      genre: "Chenda & Percussion",
      bio: "Master percussionist specialising in Chenda melam and panchavadyam. Has performed at over 200 temple festivals and cultural events.",
      imageUrl: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=600",
      city: "Perth",
      state: "WA",
      featured: false,
      cpid: generateCPID("CP-AR-"),
      performances: 210,
      slug: "vishnu-dev",
    },
    {
      name: "Anjali Thomas",
      genre: "Contemporary & Folk Painting",
      bio: "Visual artist blending Kerala mural art traditions with contemporary Australian landscapes. Exhibited at major galleries across both countries.",
      imageUrl: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=600",
      city: "Adelaide",
      state: "SA",
      featured: false,
      cpid: generateCPID("CP-AR-"),
      performances: 45,
      slug: "anjali-thomas",
    },
  ];

  const insertedArtists = await db.insert(artists).values(artistData).returning();
  for (const art of insertedArtists) {
    if (art.cpid) await db.insert(cpids).values({ cpid: art.cpid, entityType: "artist", entityId: art.id });
  }
  console.log(`Inserted ${insertedArtists.length} artists`);

  const perkData = [
    {
      title: "20% off Kerala Feast",
      description: "Get 20% off any dine-in order above $50 at Malabar Spice Kitchen. Valid for CulturePass members.",
      businessName: "Malabar Spice Kitchen",
      discount: "20%",
      code: "CPFEAST20",
      validUntil: "2026-12-31",
      category: "Food & Dining",
      imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600",
    },
    {
      title: "Free Ayurvedic Consultation",
      description: "First-time free Ayurvedic wellness consultation worth $80 at Kerala Ayurveda Wellness. Mention CulturePass at booking.",
      businessName: "Kerala Ayurveda Wellness",
      discount: "100%",
      code: "CPAYUR100",
      validUntil: "2026-09-30",
      category: "Health & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600",
    },
    {
      title: "15% off Silk Sarees",
      description: "Exclusive 15% discount on all Kasavu sarees and traditional garments. CulturePass members only.",
      businessName: "Kairali Silks",
      discount: "15%",
      code: "CPSILK15",
      validUntil: "2026-10-31",
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600",
    },
    {
      title: "Buy 1 Get 1 Chai",
      description: "Buy any premium Munnar tea blend and get a complimentary chai sampler box. In-store only.",
      businessName: "Munnar Tea Boutique",
      discount: "BOGO",
      code: "CPTEA2X",
      validUntil: "2026-08-31",
      category: "Retail",
      imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600",
    },
    {
      title: "10% off Event Photography",
      description: "Get 10% off wedding or cultural event photography packages. Book early and save more.",
      businessName: "Thejas Photography",
      discount: "10%",
      code: "CPPHOTO10",
      validUntil: "2026-12-31",
      category: "Services",
      imageUrl: "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=600",
    },
    {
      title: "$5 off Kochi Express Combo",
      description: "Flat $5 off any combo meal above $15. Available at all Kochi Express locations.",
      businessName: "Kochi Express",
      discount: "$5",
      code: "CPKOCHI5",
      validUntil: "2026-11-30",
      category: "Food & Dining",
      imageUrl: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600",
    },
  ];

  const insertedPerks = await db.insert(perks).values(perkData).returning();
  console.log(`Inserted ${insertedPerks.length} perks`);

  console.log("Database seeded successfully!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
